=head1 End Goal

This documents describes an ideal editor Kephra tries to come as close as
humanly and technically possible.

full dynamic introspection (highlighting and other services are based
on 100% behaviour of the language)

unlimited, restorable (after app restart) undo, which saves branches too and is synched
with version control integration

talk to remote tty terminal

full vi, emacs and org-mode compatibality
