=head1 Index of Kephra User Documentation


=head2 Meta : Documentation for programmer

CellularProgramming   set of rules that organizes our development
StyleGuide            programming style, where belongs what in a file
Internals             basic structure of the sources

=head2 Meta : Documentation for user


MainGoal     psychological side of our main goal 

LongFeatureList  
Components   visual components and their layout
Overview 
Philosophy 
Sanddrum     a vi like command language
Versioning   versioning schema of releases

