=head1 Kephra Overview

Welcome to the root document of the Kephra user documentation, as L<Index.pod>
is the root of the developer centric documentation.

=head2 Mission

Kephra is a tendentially fast and lightweight graphical programmers editor.
The main emphasis however lies on intelligent automation of complex tasks,
integration of your favorite tools and a wide range of configuration.
In one sentence: to make your work easier without getting in your way.

=head2 Usage

While being graphical user interface centered, Kephra tries to bring the best of
both or more worlds (aka usage like vi or emacs) [mouse, commands and key kombos].

