=head1 Index of Kephra User Documentation


CompleteProgramming	set of rules that organizes our development
Components		visual components and their layout
EndGoal			technical details of the vision we lean toward
Internals		
LongFeatureList		
Overview		
Philosophy		
Sanddrum		a vi like command language
StyleGuide		
Versioning		about our version numbers and releases

